{{ if .Values.ingress.traefik.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Release.Name }}-ingress"
  namespace: {{ .Values.namespace }}
  labels:
    app.project.name: {{ .Values.appName }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.app.domain }}`)
      services:
        - name: "{{ .Release.Name }}-service"
          port: 80
  tls:
    certResolver: default
{{- end }}