apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | toString | b64enc }}
{{- end }}
